(ns envirotech.body)

(defn exposition []
  [:div
   [:h1
    "A Breakthrough Technology for In-Situ Bitumen Recovery"]
   [:p
    "Our global energy system faces stark challenges on the horizon.  Fulfilling the generational promise of reducing poverty and creating  prosperity requires an abundance of cheap energy; but the growing threat of climate change demands that we transition to cleaner and more  sustainable forms of energy. Oil will likely still play a vital role in  our global energy system for the forseeable future"
    [:a {:href "https://www.eia.gov/todayinenergy/detail.php?id=41433"} "source"]
    " ; and so it is imperative that we begin the transition to cheaper and cleaner forms of oil recovery today."]
   [:p
    "The "
    [:em "Steam Assisted Gravity Drainage (SAGD)"]
    " technology that  powered the rise of the oil sands for over three decades has become the  root of problems that now threaten the continued survival of the  Canadian oil sands industry. Recovering unrefined bitumen using SAGD has a host of growing disadvantages; the process is complex, costly, and  energy intensive. The high CO2 emissions and poor  environmental record of SAGD has resulted in a growing political  backlash that is cutting off opportunities for continued growth."]
   [:p
    "The "
    [:em "Dimethyl Ether (DME)"]
    " based recovery technology outlined  here can become an engine of clean, sustainable growth for the Canadian  oil sands for decades to come. Dimethyl Ether is an amphoteric solvent  that displays particular affinity to bitumen. In this outline we will  see how DME based extraction can dramatically improve the recovery rate  and environmental impact, reduce the capital and operating costs, and  simplify the process of bitumen recovery. We appeal to the Canadian oil  sands industry and the governments of Alberta and Canada to work  together to demonstrate the effectiveness of this technology in order to foster a new era for the bitumen industry."]
   [:p
    [:em "All claims and figures are discussed in detail in the PDF resources located at the bottom of the page."]]])

(defn comparison []
  [:div
   [:h2 "DME versus SAGD – Summary"]
   [:h4 "DME-assisted SAGD - " [:em "DME-SA"]]
   [:p "The simplest version of the technology, and the fastest to implement.  DME-SA is based on admixing liquid  DME to steam produced by SAGD’s  plant; unless DME is to be recovered  from the dilbit, the SAGD plant  does not require modification"]
   [:h4 "DME-based Extraction - " [:em "DME-E"]]
   [:p "A standalone version of DME recovery that reduces CO2  emissions and eliminates the need for natural gas combustion, usage of  potable water, generation of steam, and treatment of process water. the  DME-E plants are supplied with DME and electric power from an offsite  facility."]
   [:h4 "Integrated DME-based Extraction - " [:em "I-DME-E"]]
   [:p "An advanced form of the technology that synchronizes the DME-E plant with an "
    [:strong "Integrated Central Facility"]
    ". Integration enables performant DME production, bitumen recovery and  partial upgrading of bitumen. The Integrated Central Facility can reduce total costs by recycling and converting all generated by-products,  including CO2,into value-added saleable products. ~90% of the unit processes utilized by the Integrated Central Facility have already been proven to be  commercially viable."]])

(defn table []
  [:div
   [:h3 "The Advantages of DME as Compared to SAGD Technology"]
   [:table
    [:thead
     [:tr
      [:th "DME as compared to SAGD"]
      [:th "DME-SA"]
      [:th "DME-E"]
      [:th "I-DME-E"]]]
    [:tbody
     [:tr
      [:td [:strong "CO2 Emission Reductions"]]
      [:td "Up To 50%"]
      [:td "~85%"]
      [:td "~100%"]]
     [:tr
      [:td [:strong "Overall Bitumen Recovery"]]
      [:td "~65%"]
      [:td "80% - 90%"]
      [:td "80% - 90%"]]
     [:tr
      [:td [:strong "Increase in Recovery Rate"]]
      [:td "~200%"]
      [:td "~300 - 400%"]
      [:td "~300 - 400%"]]
     [:tr
      [:td [:strong "Breakeven Cost Reduction"]]
      [:td "~50%"]
      [:td "~65%"]
      [:td "~80%"]]]]
   [:p "SAGD average overall recovery is 50%.*"]])


(defn pics []
  [:div
   [:p [:img {:alt "DME Picture", :src "http://envirotechdme.com/DME-Flow.png"}]]
   [:p [:img {:alt "SAGD Picture", :src "http://envirotechdme.com/SAGD-Flow.png"}]]
   [:p [:em "Select a diagram to expand it."]]
   [:p "These flow diagrams compare the input and output streams used by DME  and SAGD. Each diagram arrow represents an individual input stream or  output  stream as it moves from unit process to unit process; the  thickness of each arrow represents the approximate volume of that stream required by that technology. These diagrams demonstrate that the DME  process is simpler and more efficient at producing an equivalent volume  of bitumen compared to SAGD."]])

(defn evidence []
  [:div
   [:h2 "Evidence Supporting DME-based Extraction"]
   [:h4 "Bitumen Recovery Rates"]
   [:p [:em "Alberta Innovates 2017 Report, “Study of Solvent-Assisted In Situ Bitumen Recovery”"] " confirms that bitumen recovery rates (for DME-E) are 3.33 times higher  compared to propane and 3.94 times higher compared to butane. The report also confirms that residual bitumen saturation is higher for propane  (Fig. 8) and butane (Fig. 9) compared to DME. N-Solv has confirmed that  bitumen output from a propane/butane extraction plant operating at 50C  is comparable to a SAGD plant."]
   [:p [:em "Canadian Patent #2,652,930"] " shows that extraction of oil  sands ore with liquid DME at 50C and 1.2 MPa pressure reduces the  bitumen content in the bituminous ore from 11.8wt% to 0.2wt% in the dry  residue – a reduction of over 98wt%."]
   [:h4 "Energy Consumption & CO2 Emissions"]
   [:p [:em "METI 2009 Interim Report Alberta Bitumen Link (ABL)"] " shows  on page 22 how a DME-E plant consumes 6.2-8.5% of the energy required by an equivalent SAGD plant. On page 26 the report shows that total DME-E  plant emissions of CO2 amount to approximately 4% of SAGD’s plant."]
   [:h4 "Fluid Mass Flow"]
   [:p [:em "METI 2009 Interim Report “Alberta Bitumen Link (ABL)"] " shows  on page 25 that for an equivelant yield of bitumen/day, a SAGD plant  will require 30 times the flow of injection fluids then what is required for a DME plant."]
   [:h4 "SAGD Steam Distribution in Reservoir"]
   [:p [:em "I. Gates, J. Adams and S. Larter, (CSEG Recorder, 33, (7), 42-48, 2008)"] " concluded that in a reservoir the steam is distributed chiefly via  channels and fractures; cementation and consolidated character of the  reservoir will impede steam flow and heat distribution; extension of  channels and fractures beyond the gravity drainage chamber will cause  heat losses; excessive accumulation of water in the reservoir is known  to result in unacceptable heat losses."]
   [:h4 "DME Solvent Distriution in Reservoir"]
   [:p [:em "F. Diedro, J. Bryan, S. Kryuchkow and A. Kantzas, (publication SPE-174424-MS, Calgary, 9-11 June, 2015)"] " confirmed that DME displays maximum solubility, faster mass transfer  and also considerably more swelling as compared to propane, pentane and  toluene; the authors have concluded that DME has the potential for use  as a solvent in heavy oil and bitumen recovery in vapor as well as  liquid phases."]
   [:h4 "DME potential for bitumen recovery"]
   [:p [:em "A. Haddadnia, M. Zirahhi, H. Hassanzadeh and J. Abedi, (Canada  Heavy Oil Technical Conference, Calgary, AB, Canada, 13-14 March, 2018)"] " confirmed the potential of DME as a solvent for use with ES-SAGD (Expanding Solvent SAGD)."]
   [:h4 "Reduced Complexity of Solvent Based Extraction"]
   [:p [:em "GE Heavy Oil Solutions Group, 2012 Watertech. Conference, Calgary, AB, Canada"] " showed that the need for natural gas combustion, high temperature  pressurized steam and process water treatment hardware is essential for  the operation of a SAGD plant, but eliminated for a solvent based plant."]])

(defn hydrogen []
  [:div
    [:h3 "The Potential for the Hydrogen Economy"]
   [:p "DME is the key to significantly improving the environmental and  economic performance of the in-situ bitumen recovery industry (see B).  DME handling, including storage pipelining and shipping does not present problems associated with LNG handling. The existing Liquefied Petroleum Gas (LPG) infrastructure is suitable for DME. Steam reforming of DME,  as compared to LNG reforming, generates larger volumes of hydrogen and  proceeds under much milder conditions. A blend of CO2/H2O can be converted to DME by catalytic photosynthesis (see D) and  successful scale-up of this process would result in a drastic reduction  of the DME production cost. In Alberta, DME has the potential to bridge  the transition from fossil fuels to the hydrogen economy."]])

#_(defn accordion []
  [:div {:class "relative mb-3"}
   [:h6 {:class "mb-0"}
    [:button {:class ["border-slate-100 text-slate-700 rounded-t-1 group relative flex w-full cursor-pointer items-center border-b border-solid p-4 text-left font-semibold text-dark-500 transition-all ease-in"], :data-collapse-target "collapse-1"}
     [:span "What is Material Tailwind?"]
     [:i {:class "fa fa-plus absolute right-0 pt-1 text-xs group-open:opacity-0"}]
     [:i {:class "fa fa-minus absolute right-0 pt-1 text-xs opacity-0 group-open:opacity-100"}]]]
   [:div {:data-collapse "collapse-1", :class "h-0 overflow-hidden transition-all duration-300 ease-in-out"}
    [:div {:class "p-4 text-sm leading-normal text-blue-gray-500/80"} "We&#39;re not always in the position that we want to be at. We&#39;re constantly\n      growing. We&#39;re constantly making mistakes. We&#39;re constantly trying to\n      express ourselves and actualize our dreams."]]])

(defn collapsible []
  [:details
   [:summary {:class ["list-none" "flex" "flex-wrap" "items-center" ]}
    [:h3 {:class ["flex" "flex-1" "p-4" "font-semibold"]} "Click me for drop down!"]
    [:div {:class ["flex" "w-10" "items-center" "justify-center"]}
     [:div {:class [:border-8 "border-transparent"]}]]]
   [:div [:p "Lorum ipsum dolor sit, amet consectetur adipisicing elit..."]]])

(defn coll2 []
  [:details {:class "bg-white shadow rounded group mb-4"}
   [:summary {:class "list-none flex flex-wrap items-center cursor-pointer\n    focus-visible:outline-none focus-visible:ring focus-visible:ring-pink-500\n    rounded group-open:rounded-b-none group-open:z-
            [1]relative"}
    [:h3 {:class "flex flex-1 p-4 font-semibold"} "Check out this example"]
    [:div {:class "flex w-10 items-center justify-center"}
     [:div {:class "border-8 border-transparent border-l-gray-600 ml-2\n        group-open:rotate-90 transition-transform origin-left"}]]]
   [:div {:class "p-4"}
    [:p "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsum praesentium officia nostrum iste eaque,\n        explicabo sunt, voluptatum mollitia corporis porro repudiandae. Eaque neque voluptatum sint molestiae? Assumenda\n        eligendi facilis reprehenderit."]]])

(defn footer []
  [:p.my-5 "THIS IS THE END OF THE PAGE"])

(defn text []
  [:div [:article {:class ["prose" "mt-5"]}
         [exposition]
         [comparison]
         [table]
         [pics]
         [evidence]]
   #_[accordion]
   #_[collapsible]
   [coll2]
   #_[hydrogen]
   [footer]])
